export interface Project {
  id: string
  title: string
  description: string
  longDescription: string
  tech: string[]
  tags: string[]
  category: "web-development" | "learning"
  type: "client" | "personal"
  status: "Live" | "Completed" | "In Development"
  url?: string
  github?: string
  image: string
  images?: string[]
  features: string[]
  challenges?: string[]
  year: string
  client?: string
  slug: string
}

export const projects: Project[] = [
  // Client Projects
  {
    id: "reddot",
    slug: "reddot",
    title: "Reddot",
    description: "Commercial website for a printing and design solutions company.",
    longDescription:
      "A professional WordPress website for Reddot, a comprehensive printing and design solutions company. The site showcases their full range of services including digital printing, graphic design, branding solutions, and custom merchandise. Features a modern design, service portfolio, client testimonials, and integrated contact systems for seamless customer engagement.",
    tech: ["WordPress"],
    tags: ["WordPress", "Business Website", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://reddotbiz.com",
    image: "/images/projects/reddot-hero.jpg",
    images: [
      "/images/projects/reddot-hero.jpg",
      "/images/projects/reddot-services.jpg",
      "/images/projects/reddot-portfolio.jpg",
    ],
    features: [
      "Custom WordPress theme development",
      "Service showcase with detailed descriptions",
      "Portfolio gallery with filtering",
      "Client testimonials and reviews",
      "Contact forms with email integration",
      "SEO optimization for local search",
      "Mobile-responsive design",
      "Fast loading performance",
    ],
    challenges: [
      "Creating a design that appeals to diverse business clients",
      "Optimizing WordPress for fast loading times",
      "Implementing effective local SEO strategies",
    ],
    year: "2024",
    client: "Reddot Business Solutions",
  },
  {
    id: "teachers-by-choice",
    slug: "teachers-by-choice",
    title: "Teachers By Choice",
    description: "Tutoring platform to match students with private educators.",
    longDescription:
      "An innovative educational platform built with Next.js that connects students with qualified private tutors. The platform features advanced matching algorithms, integrated scheduling systems, secure payment processing, and comprehensive user management for both students and educators. Built with modern web technologies for optimal performance and user experience.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Web App", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://teachersbychoice.vercel.app/",
    image: "/images/projects/teachers-hero.jpg",
    images: [
      "/images/projects/teachers-hero.jpg",
      "/images/projects/teachers-dashboard.jpg",
      "/images/projects/teachers-matching.jpg",
    ],
    features: [
      "Advanced tutor-student matching algorithm",
      "Integrated scheduling and booking system",
      "Secure user authentication and profiles",
      "Real-time messaging and communication",
      "Payment processing integration",
      "Review and rating system",
      "Subject and skill filtering",
      "Mobile-responsive design",
    ],
    challenges: [
      "Developing complex matching algorithms for optimal tutor-student pairing",
      "Implementing secure payment processing",
      "Creating intuitive interfaces for both user types",
    ],
    year: "2024",
    client: "Teachers By Choice",
  },
  {
    id: "charge-infra",
    slug: "charge-infra",
    title: "Charge Infra",
    description: "EV infrastructure website for showcasing solutions.",
    longDescription:
      "A modern landing page for Charge Infra, showcasing their electric vehicle charging infrastructure solutions. Built with Next.js and Tailwind CSS, the site features interactive elements, service information, and a clean, professional design that reflects the company's commitment to sustainable transportation and innovative charging solutions.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Landing Page", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://charge-infra-liard.vercel.app/",
    image: "/images/projects/charge-infra-hero.jpg",
    features: [
      "Modern, clean landing page design",
      "Interactive service showcases",
      "Responsive design for all devices",
      "Fast loading performance",
      "SEO optimization",
      "Contact and inquiry forms",
      "Professional imagery and graphics",
      "Smooth scrolling animations",
    ],
    challenges: [
      "Creating compelling visuals for technical infrastructure",
      "Balancing information density with clean design",
      "Optimizing for mobile users in the EV industry",
    ],
    year: "2024",
    client: "Charge Infrastructure",
  },
  {
    id: "tuff-ppf",
    slug: "tuff-ppf",
    title: "Tuff PPF",
    description: "Website for an automotive paint protection film business.",
    longDescription:
      "A specialized WordPress website for Tuff PPF, an automotive paint protection film service provider. The site showcases their expertise in vehicle protection, features a comprehensive service gallery, customer testimonials, and booking systems for consultations and services. Designed to build trust and showcase quality workmanship in the automotive protection industry.",
    tech: ["WordPress"],
    tags: ["WordPress", "Business Website", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://tuffppf.com/",
    image: "/images/projects/tuff-ppf-hero.jpg",
    images: [
      "/images/projects/tuff-ppf-hero.jpg",
      "/images/projects/tuff-ppf-gallery.jpg",
      "/images/projects/tuff-ppf-services.jpg",
    ],
    features: [
      "Custom WordPress theme for automotive industry",
      "Before/after gallery showcasing work quality",
      "Service descriptions with pricing information",
      "Customer testimonials and reviews",
      "Online booking and consultation forms",
      "Mobile-optimized design",
      "Local SEO optimization",
      "Social media integration",
    ],
    challenges: [
      "Showcasing visual work quality effectively online",
      "Building trust through testimonials and portfolio",
      "Optimizing for local automotive service searches",
    ],
    year: "2023",
    client: "Tuff PPF",
  },

  // IT Consulting & Business Solutions
  {
    id: "bricstal-tech",
    slug: "bricstal-tech",
    title: "Bricstal Tech",
    description: "Corporate website for an IT consulting firm showcasing technology services and solutions.",
    longDescription: "A comprehensive web application for Bricstal Tech, an IT consulting firm, built with Next.js. The website showcases industry-specific solutions, innovative technology services, and business offerings with a modern, professional design optimized for lead generation and corporate branding.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Business Website", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.bricstaltech.com/",
    image: "/images/projects/bricstal-tech-hero.jpg",
    features: ["Professional corporate website design", "Service showcase with detailed descriptions", "Team and leadership section", "Contact and inquiry forms", "SEO optimization", "Mobile-responsive layout", "Fast performance with Next.js", "Modern UI with smooth animations"],
    challenges: ["Communicating complex IT services in a user-friendly way", "Creating a professional enterprise-level design", "Optimizing for lead generation"],
    year: "2024",
    client: "Bricstal Tech",
  },
  {
    id: "bricstal-group",
    slug: "bricstal-group",
    title: "Bricstal Group",
    description: "Multi-company group website presenting the Bricstal brand umbrella and subsidiaries.",
    longDescription: "A high-performance Next.js website for the Bricstal Group, serving as the central hub for all group companies and subsidiaries. Features a professional corporate design, company overview, group structure, and seamless navigation between different business units under the Bricstal brand.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Corporate", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.bricstal.com/",
    image: "/images/projects/bricstal-group-hero.jpg",
    features: ["Corporate group identity design", "Subsidiary companies showcase", "Leadership and about sections", "Multi-page navigation", "Professional animations", "SEO optimized structure", "Mobile-responsive design", "Fast-loading Next.js architecture"],
    challenges: ["Representing multiple subsidiaries under one umbrella", "Creating a cohesive brand identity across sections", "Managing complex information architecture"],
    year: "2024",
    client: "Bricstal Group",
  },
  {
    id: "bricstal-research",
    slug: "bricstal-research",
    title: "Bricstal Research",
    description: "R&D division website for Bricstal Group showcasing research initiatives and innovations.",
    longDescription: "A specialized Next.js website for Bricstal Research, the R&D arm of Bricstal Group. The site highlights research initiatives, innovations, publications, and technical capabilities, presenting the organization's commitment to advancing technology solutions through dedicated research and development.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Research", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.brain.bricstal.com/",
    image: "/images/projects/bricstal-research-hero.jpg",
    features: ["Research initiatives showcase", "Innovation and publications section", "Team and expertise profiles", "Technical capabilities overview", "Professional academic design", "SEO optimized content", "Mobile-responsive layout"],
    challenges: ["Presenting technical research in an accessible way", "Maintaining brand consistency with the group website", "Designing for a technical audience"],
    year: "2024",
    client: "Bricstal Group",
  },
  {
    id: "bricstal-foundation",
    slug: "bricstal-foundation",
    title: "Bricstal Foundation",
    description: "Foundation website for Bricstal Group's CSR and social impact initiatives.",
    longDescription: "A purpose-driven Next.js website for Bricstal Foundation, the CSR arm of Bricstal Group. The site communicates the foundation's mission, programs, and social impact efforts, with a warm and professional design that builds trust and encourages community engagement.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "NGO", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.bricstalfoundation.com/",
    image: "/images/projects/bricstal-foundation-hero.jpg",
    features: ["Mission and impact storytelling", "Programs and initiatives showcase", "News and updates section", "Mobile-responsive design", "Accessible and inclusive design", "SEO optimization"],
    challenges: ["Communicating social impact effectively", "Balancing corporate branding with non-profit warmth", "Building trust through content design"],
    year: "2024",
    client: "Bricstal Group",
  },
  {
    id: "bricstal-investor-portal",
    slug: "bricstal-investor-portal",
    title: "Bricstal Investor Portal",
    description: "Secure investor management portal for Bricstal Group with Firebase backend.",
    longDescription: "A secure, feature-rich investor portal built with Next.js and Firebase for Bricstal Group. The platform provides investors with real-time access to portfolio data, reports, and investment management tools, featuring secure authentication, role-based access control, and a professional dashboard interface.",
    tech: ["Next.js", "Firebase", "Tailwind CSS"],
    tags: ["Next.js", "Firebase", "Tailwind CSS", "Web App", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://investor.bricstal.com/",
    image: "/images/projects/bricstal-investor-hero.jpg",
    features: ["Secure investor authentication", "Real-time portfolio dashboard", "Investment reports and analytics", "Role-based access control", "Firebase real-time database", "Document management system", "Mobile-responsive interface", "Professional financial data display"],
    challenges: ["Implementing secure financial data access", "Designing intuitive investment dashboards", "Managing real-time data with Firebase"],
    year: "2024",
    client: "Bricstal Group",
  },

  // Construction & Real Estate
  {
    id: "neo-heights",
    slug: "neo-heights",
    title: "Neo Heights",
    description: "Industrial construction company website showcasing projects and services.",
    longDescription: "A modern Next.js website integrated with Drupal CMS for Neo Heights, an industrial construction company. The site showcases major construction projects, engineering capabilities, team expertise, and services with a bold, professional design that reflects the company's strength and reliability.",
    tech: ["Next.js", "Drupal", "Tailwind CSS"],
    tags: ["Next.js", "Drupal", "Tailwind CSS", "Construction", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://neo-heights.vercel.app/",
    image: "/images/projects/neo-heights-hero.jpg",
    features: ["Project portfolio with case studies", "Services and capabilities showcase", "Team and leadership profiles", "Drupal CMS for content management", "Contact and inquiry forms", "Mobile-responsive design", "SEO optimization", "High-performance Next.js architecture"],
    challenges: ["Integrating Next.js frontend with Drupal CMS", "Showcasing large-scale construction projects effectively", "Optimizing image-heavy construction portfolio"],
    year: "2024",
    client: "Neo Heights",
  },
  {
    id: "prasiddhi-cloud9",
    slug: "prasiddhi-cloud9",
    title: "Prasiddhi Cloud 9",
    description: "Real estate landing page for a premium residential project campaign.",
    longDescription: "A high-converting real estate landing page built with Next.js for Prasiddhi Cloud 9, a premium residential development. The page features compelling property showcases, amenities highlights, floor plan visualizations, and integrated lead capture forms designed to drive inquiries.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Real Estate", "Landing Page", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://campaign.prasiddhigroup.com/",
    image: "/images/projects/prasiddhi-hero.jpg",
    features: ["Premium property showcase design", "Amenities and features highlights", "Floor plan visualization", "Lead capture forms", "Smooth scroll animations", "Mobile-optimized layout", "Fast loading performance", "SEO for real estate"],
    challenges: ["Creating a high-converting landing page", "Showcasing property features effectively", "Optimizing for mobile real estate browsers"],
    year: "2024",
    client: "Prasiddhi Group",
  },
  {
    id: "iconhomz",
    slug: "iconhomz",
    title: "Iconhomz",
    description: "WordPress website for a residential construction and real estate company.",
    longDescription: "A professional WordPress website for Iconhomz, a residential construction and real estate company. The site showcases residential projects, construction capabilities, floor plans, and pricing information with a clean, trust-building design that helps potential buyers make informed decisions.",
    tech: ["WordPress"],
    tags: ["WordPress", "Real Estate", "Construction", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.iconhomz.com/",
    image: "/images/projects/iconhomz-hero.jpg",
    features: ["Residential project showcases", "Floor plan and pricing displays", "Lead generation forms", "Customer testimonials", "SEO optimization for real estate", "Mobile-responsive design", "Custom WordPress theme"],
    challenges: ["Presenting complex real estate information clearly", "Optimizing for local real estate searches", "Building buyer trust through design"],
    year: "2023",
    client: "Iconhomz",
  },
  {
    id: "yuvi-builders",
    slug: "yuvi-builders",
    title: "Yuvi Builders",
    description: "Real estate and construction firm website with Drupal CMS integration.",
    longDescription: "An advanced web platform for Yuvi Builders, a real estate and construction firm, built with Next.js and integrated with Drupal CMS for content management. Features project showcases, property listings, construction portfolio, and inquiry systems with a professional design that builds credibility.",
    tech: ["Next.js", "Drupal", "Tailwind CSS"],
    tags: ["Next.js", "Drupal", "Tailwind CSS", "Real Estate", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.yuvibuilders.com/",
    image: "/images/projects/yuvi-builders-hero.jpg",
    features: ["Project portfolio with case studies", "Property listings and showcases", "Drupal CMS for content updates", "Inquiry and booking forms", "Team and expertise profiles", "SEO optimization", "Mobile-responsive design"],
    challenges: ["Integrating Next.js with Drupal CMS", "Managing large property image galleries", "Creating effective property showcase layouts"],
    year: "2024",
    client: "Yuvi Builders",
  },

  // Interior Design & Furniture
  {
    id: "tassels-interior",
    slug: "tassels-interior",
    title: "Tassels Interior",
    description: "Premium interior products and design solutions showcase website.",
    longDescription: "A sophisticated Next.js website for Tassels, a premium interior products company. The site features a curated showcase of interior design products, project galleries, and design inspiration with an elegant, visually-driven design that appeals to high-end residential and commercial clients.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Interior Design", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.tasselsinterior.com/",
    image: "/images/projects/tassels-hero.jpg",
    features: ["Premium product catalogue showcase", "Project portfolio and galleries", "Design inspiration sections", "Contact and consultation forms", "Elegant visual design", "Mobile-responsive layout", "Fast-loading image galleries", "SEO optimized content"],
    challenges: ["Creating a luxury feel through web design", "Optimizing high-resolution interior imagery", "Building an intuitive product showcase"],
    year: "2024",
    client: "Tassels Interior",
  },
  {
    id: "neo-leather",
    slug: "neo-leather",
    title: "Neo Leather",
    description: "Modern web platform for a premium leather furniture company.",
    longDescription: "A modern, high-performance website for Neo Leather, a premium leather furniture company, built with Next.js. The static site showcases personalized leather furniture offerings with an elegant design, product galleries, and detailed craftsmanship highlights that communicate quality and exclusivity.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Furniture", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://neoleather.in/",
    image: "/images/projects/neo-leather-hero.jpg",
    features: ["Premium product showcase design", "Leather furniture catalogue", "Craftsmanship highlight sections", "Customer inquiry forms", "Elegant visual aesthetic", "High-performance static pages", "Mobile-responsive design", "SEO optimization"],
    challenges: ["Conveying leather quality through digital imagery", "Designing for a luxury furniture audience", "Optimizing product photography displays"],
    year: "2024",
    client: "Neo Leather",
  },
  {
    id: "look-and-live",
    slug: "look-and-live",
    title: "Look and Live",
    description: "Interior design firm website showcasing design projects and services.",
    longDescription: "A stylish Next.js website for Look and Live, a professional interior design firm. The site beautifully presents the firm's portfolio of completed design projects, services, team expertise, and design philosophy with a visually striking layout that demonstrates creative excellence.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Interior Design", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.lookandlive.in/",
    image: "/images/projects/look-and-live-hero.jpg",
    features: ["Design portfolio with project galleries", "Services and specializations showcase", "Team profiles and expertise", "Client testimonials", "Contact and consultation forms", "Visually-driven layout", "Mobile-responsive design"],
    challenges: ["Letting the visual work speak for itself", "Creating intuitive portfolio navigation", "Balancing aesthetics with usability"],
    year: "2024",
    client: "Look and Live",
  },
  {
    id: "antara-studios",
    slug: "antara-studios",
    title: "Antara Studios",
    description: "Interior design and architectural firm website with turnkey project showcases.",
    longDescription: "A comprehensive website for Antara Studios, an interior design and architectural firm, built with WordPress and Elementor. The site showcases turnkey interior projects, architecture, construction, renovation, and landscaping services with a sophisticated design that communicates full-service capabilities.",
    tech: ["WordPress"],
    tags: ["WordPress", "Interior Design", "Architecture", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://antarastudios.in/",
    image: "/images/projects/antara-studios-hero.jpg",
    features: ["Portfolio of completed design projects", "Multi-service showcase", "Architecture and interior galleries", "Client testimonials", "Project inquiry forms", "SEO optimization", "Mobile-responsive design", "Custom WordPress design"],
    challenges: ["Showcasing diverse design services cohesively", "Managing large portfolio image galleries", "Creating a premium brand feel with WordPress"],
    year: "2023",
    client: "Antara Studios",
  },

  // Healthcare & Wellness
  {
    id: "dr-yasaswis",
    slug: "dr-yasaswis",
    title: "Dr. Yasaswis Dental Clinic",
    description: "Professional dental clinic website with appointment booking and services.",
    longDescription: "A professional WordPress website for Dr. Yasaswis Dental Clinic, providing patients with comprehensive information about dental services, doctor profiles, treatment procedures, and easy appointment booking. The site builds trust through clear medical information, team credentials, and patient testimonials.",
    tech: ["WordPress"],
    tags: ["WordPress", "Healthcare", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://dryasaswis.com/",
    image: "/images/projects/dr-yasaswis-hero.jpg",
    features: ["Dental services showcase", "Doctor profiles and credentials", "Appointment booking system", "Treatment procedure information", "Patient testimonials", "Before/after treatment gallery", "Local SEO optimization", "Mobile-responsive design"],
    challenges: ["Presenting medical information clearly and accessibly", "Building patient trust through design", "Optimizing for local dental service searches"],
    year: "2024",
    client: "Dr. Yasaswis Dental Clinic",
  },
  {
    id: "shreya-hearing-clinic",
    slug: "shreya-hearing-clinic",
    title: "Shreya Hearing Clinic",
    description: "Hearing aids and audiology clinic website with service information.",
    longDescription: "A compassionate and informative Next.js website for Shreya Hearing Clinic, specializing in hearing aids and audiology services. The site provides clear information about hearing conditions, available products, treatment options, and clinic services with a warm, accessible design that builds trust with patients.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Healthcare", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://shreya-hearings.vercel.app/",
    image: "/images/projects/shreya-hearing-hero.jpg",
    features: ["Hearing aid product showcase", "Audiology services information", "Appointment and consultation booking", "Patient education resources", "Doctor and team profiles", "Contact and location details", "Mobile-responsive design", "SEO optimization"],
    challenges: ["Designing for accessibility and ease of use", "Presenting medical products clearly", "Building patient confidence through design"],
    year: "2024",
    client: "Shreya Hearing Clinic",
  },
  {
    id: "vedaearth-lounge-spa",
    slug: "vedaearth-lounge-spa",
    title: "VedaEarth Lounge Spa",
    description: "Premium women's lounge spa website with WordPress and Zoho Creator POS.",
    longDescription: "An elegant WordPress website for VedaEarth Lounge Spa, a premium women's wellness and beauty lounge. Integrated with Zoho Creator for point-of-sale and appointment management, the site showcases spa services, wellness treatments, ambiance, and membership packages with a luxurious aesthetic.",
    tech: ["WordPress"],
    tags: ["WordPress", "Wellness", "Spa", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://vedaearthloungespa.com/",
    image: "/images/projects/vedaearth-hero.jpg",
    features: ["Spa services and treatment showcase", "Online appointment booking", "Zoho Creator POS integration", "Membership and package displays", "Ambiance and gallery sections", "Luxury aesthetic design", "Mobile-responsive layout", "Local SEO optimization"],
    challenges: ["Conveying a luxury spa experience digitally", "Integrating Zoho Creator for POS", "Designing for a women-first audience"],
    year: "2024",
    client: "VedaEarth Lounge Spa",
  },
  {
    id: "snip-dark-salon",
    slug: "snip-dark-salon",
    title: "Snip Dark Salon Spa",
    description: "Premium dark-themed website for a luxury salon and spa.",
    longDescription: "A premium website for Snip Dark Salon Spa, showcasing luxury spa services, unique dark aesthetic, and expertise with a sleek design built on WordPress and Elementor. Features service catalogues, team profiles, booking integration, and a gallery that captures the salon's distinctive premium atmosphere.",
    tech: ["WordPress"],
    tags: ["WordPress", "Salon", "Spa", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://snipdark.com/",
    image: "/images/projects/snip-dark-hero.jpg",
    features: ["Luxury dark-themed website design", "Service and treatment catalogue", "Online booking integration", "Team stylist profiles", "Gallery and ambiance showcase", "Membership and package offers", "Mobile-responsive design", "Local SEO optimization"],
    challenges: ["Translating the dark luxury aesthetic to web", "Showcasing premium services effectively", "Optimizing for local salon searches"],
    year: "2023",
    client: "Snip Dark Salon Spa",
  },
  {
    id: "bangalore-gastro-centre",
    slug: "bangalore-gastro-centre",
    title: "Bangalore Gastro Centre",
    description: "Comprehensive hospital website with specialist information and appointment booking.",
    longDescription: "A comprehensive website for the Bangalore Gastro Centre, built with Next.js and integrated with Drupal CMS. Features information about medical specialities, doctor profiles, appointment booking systems, patient resources, and blog content, creating a trustworthy digital presence for a leading gastroenterology hospital.",
    tech: ["Next.js", "Drupal", "Tailwind CSS"],
    tags: ["Next.js", "Drupal", "Tailwind CSS", "Healthcare", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://bangaloregastrocentre.com/",
    image: "/images/projects/bgc-hero.jpg",
    features: ["Medical specialities showcase", "Doctor profiles and credentials", "Online appointment booking", "Patient education resources", "Blog and health articles", "Drupal CMS integration", "Mobile-responsive design", "Healthcare SEO optimization"],
    challenges: ["Presenting complex medical information accessibly", "Integrating appointment booking with Drupal", "Building patient trust through design"],
    year: "2023",
    client: "Bangalore Gastro Centre",
  },

  // Automotive
  {
    id: "sangeetha-tyres",
    slug: "sangeetha-tyres",
    title: "Sangeetha Tyres",
    description: "Full-featured automotive services website with Firebase backend.",
    longDescription: "A feature-rich Next.js website with Firebase backend for Sangeetha Tyres, a comprehensive automotive services provider. The platform allows customers to browse tyre catalogues, book service appointments, get quotes, and access automotive care information with real-time data management.",
    tech: ["Next.js", "Firebase", "Tailwind CSS"],
    tags: ["Next.js", "Firebase", "Tailwind CSS", "Automotive", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.sangeethatyres.in/",
    image: "/images/projects/sangeetha-tyres-hero.jpg",
    features: ["Tyre product catalogue", "Service appointment booking", "Quote request system", "Firebase real-time backend", "Brand and product filtering", "Customer portal", "Mobile-responsive design", "Local SEO optimization"],
    challenges: ["Managing large product catalogues efficiently", "Implementing real-time appointment booking", "Designing for automotive service customers"],
    year: "2024",
    client: "Sangeetha Tyres",
  },
  {
    id: "turbo-car-care",
    slug: "turbo-car-care",
    title: "Turbo Car Care",
    description: "WordPress website for a premium car coating and detailing service.",
    longDescription: "A visually stunning WordPress website for Turbo Car Care, specialists in premium car coating and detailing services. The site showcases service expertise, before/after galleries, pricing packages, and booking options with a bold, automotive-inspired design that appeals to car enthusiasts.",
    tech: ["WordPress"],
    tags: ["WordPress", "Automotive", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.turbocarcare.in/",
    image: "/images/projects/turbo-car-care-hero.jpg",
    features: ["Car coating service showcase", "Before/after project gallery", "Service packages and pricing", "Online booking and inquiry forms", "Customer testimonials", "Local SEO optimization", "Mobile-responsive design", "Custom WordPress theme"],
    challenges: ["Showcasing vehicle transformation visually", "Communicating premium service quality online", "Optimizing for local automotive searches"],
    year: "2024",
    client: "Turbo Car Care",
  },

  // Handmade & Specialty Products
  {
    id: "maatikosh",
    slug: "maatikosh",
    title: "Maatikosh",
    description: "Shopify e-commerce store for handmade ceramic products and artisanal crafts.",
    longDescription: "A beautifully crafted Shopify e-commerce store for Maatikosh, a brand specializing in handmade ceramic products. The store features an earthy, artisanal aesthetic with curated product collections, detailed product stories, craft process showcases, and a seamless shopping experience.",
    tech: ["Shopify"],
    tags: ["Shopify", "E-commerce", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://maatikosh.com/",
    image: "/images/projects/maatikosh-hero.jpg",
    features: ["Custom Shopify storefront design", "Handmade product collections", "Craft process storytelling", "Secure payment processing", "Product search and filtering", "Mobile-optimized shopping", "Inventory management", "SEO for artisan products"],
    challenges: ["Conveying handmade quality through digital storefronts", "Optimizing product photography presentation", "Creating a seamless artisan shopping experience"],
    year: "2024",
    client: "Maatikosh",
  },
  {
    id: "ramya-katta-couture",
    slug: "ramya-katta-couture",
    title: "Ramya Katta Couture",
    description: "Shopify fashion e-commerce store for designer clothing and couture collections.",
    longDescription: "A premium Shopify e-commerce store for Ramya Katta Couture, a designer clothing brand. The store showcases exclusive couture collections with an elegant, fashion-forward design featuring lookbooks, collection launches, size guides, and a seamless checkout experience for fashion-conscious shoppers.",
    tech: ["Shopify"],
    tags: ["Shopify", "E-commerce", "Fashion", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://ramyakatta.com/",
    image: "/images/projects/ramya-katta-hero.jpg",
    features: ["Premium fashion storefront design", "Designer collection showcases", "Lookbook and editorial sections", "Size guide and product details", "Secure Shopify checkout", "Mobile-responsive shopping", "Inventory and variant management", "Fashion SEO optimization"],
    challenges: ["Capturing designer brand aesthetics digitally", "Managing complex clothing variants", "Creating compelling fashion editorial layouts"],
    year: "2024",
    client: "Ramya Katta Couture",
  },
  {
    id: "miracle-stonex",
    slug: "miracle-stonex",
    title: "Miracle Stonex",
    description: "React.js website for a granite and stone products manufacturing company.",
    longDescription: "A professional React.js website for Miracle Stonex, a manufacturer and supplier of premium granite and stone products. The site showcases their extensive product catalogue, manufacturing capabilities, project references, and quality certifications with a clean, industrial design for architects and contractors.",
    tech: ["React.js", "Tailwind CSS"],
    tags: ["React.js", "Tailwind CSS", "Manufacturing", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.miraclestonex.com/",
    image: "/images/projects/miracle-stonex-hero.jpg",
    features: ["Granite and stone product catalogue", "Manufacturing capabilities showcase", "Project reference gallery", "Quality certifications section", "Inquiry and quotation forms", "Product filtering and search", "Mobile-responsive design", "SEO optimization"],
    challenges: ["Showcasing natural stone products digitally", "Building a B2B-focused user experience", "Managing extensive product catalogues"],
    year: "2024",
    client: "Miracle Stonex",
  },
  {
    id: "playgram",
    slug: "playgram",
    title: "Playgram",
    description: "Comprehensive web platform for a professional sports coaching academy.",
    longDescription: "A comprehensive web platform for Playgram, a professional sports coaching academy specializing in youth training. Built with Next.js and Supabase, the platform offers expert-led coaching programs, sports training schedules, enrollment systems, coach profiles, and performance tracking for young athletes.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Next.js", "Tailwind CSS", "Sports", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://playgram.in/",
    image: "/images/projects/playgram-hero.jpg",
    features: ["Sports program and schedule showcase", "Coach profiles and credentials", "Student enrollment system", "Performance tracking features", "Parent and student portals", "Mobile-responsive design", "Event and tournament information"],
    challenges: ["Designing for both parents and young athletes", "Managing scheduling and enrollment data", "Creating engaging sports-focused UI"],
    year: "2024",
    client: "Playgram",
  },

  // Learning & Exploration Projects
  {
    id: "cyberquest",
    slug: "cyberquest",
    title: "CyberQuest",
    description:
      "An immersive capture-the-flag treasure hunt challenge designed with cybersecurity puzzles like SQL injection, steganography, maze-solving, and terminal emulation.",
    longDescription:
      "An immersive capture-the-flag treasure hunt challenge designed with cybersecurity puzzles like SQL injection, steganography, maze-solving, and terminal emulation. Built for a university event to provide hands-on cybersecurity education in a gamified environment. Features multiple challenge types, progressive difficulty, and real-time scoring systems.",
    tech: ["Next.js", "Tailwind CSS", "HTML/CSS/JS"],
    tags: ["Next.js", "Tailwind CSS", "HTML/CSS/JS", "Puzzle Game"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/cyberquest-hero.jpg",
    images: [
      "/images/projects/cyberquest-hero.jpg",
      "/images/projects/cyberquest-terminal.jpg",
      "/images/projects/cyberquest-maze.jpg",
      "/images/projects/cyberquest-constellation.jpg",
    ],
    features: [
      "SQL Injection challenge simulation",
      "Steganography puzzle solving",
      "Terminal-based authentication challenges",
      "Interactive maze navigation",
      "Constellation pattern recognition",
      "Progressive difficulty levels",
      "Real-time scoring system",
      "Educational hints and explanations",
    ],
    challenges: [
      "Creating realistic cybersecurity scenarios in a safe environment",
      "Balancing educational value with engaging gameplay",
      "Implementing complex algorithms for puzzle generation",
    ],
    year: "2024",
  },
  {
    id: "ecommerce-dashboard",
    slug: "ecommerce-dashboard",
    title: "E-commerce Dashboard",
    description:
      "A simple e-commerce admin panel with analytics, order tracking, inventory and user management. Built to practice data visualization and component layout in React.",
    longDescription:
      "A comprehensive e-commerce admin dashboard built with React.js to practice data visualization and component architecture. Features analytics charts, order tracking, inventory management, and user administration. Designed with Material-UI components and Chart.js for professional data presentation and intuitive user experience.",
    tech: ["React.js", "HTML/CSS/JS"],
    tags: ["React.js", "HTML/CSS/JS", "Dashboard"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/dashboard-hero.jpg",
    images: [
      "/images/projects/dashboard-overview.jpg",
      "/images/projects/dashboard-orders.jpg",
      "/images/projects/dashboard-analytics.jpg",
    ],
    features: [
      "Real-time sales analytics and charts",
      "Order tracking and management",
      "Inventory management system",
      "User administration panel",
      "Revenue and performance metrics",
      "Responsive dashboard layout",
      "Data visualization with Chart.js",
      "Material-UI component library",
    ],
    challenges: [
      "Implementing efficient data visualization",
      "Creating responsive dashboard layouts",
      "Managing complex state across multiple components",
    ],
    year: "2024",
  },
  {
    id: "task-management-system",
    slug: "task-management-system",
    title: "Task Management System",
    description:
      "Kanban-style productivity tool for managing tasks collaboratively. Includes real-time updates, progress tracking, and team assignment.",
    longDescription:
      "A Kanban-style productivity application built with React and Firebase for collaborative task management. Features real-time updates, progress tracking, team assignment, and drag-and-drop functionality. Styled with Tailwind CSS for a modern, responsive interface that works seamlessly across devices.",
    tech: ["React.js", "Tailwind CSS", "HTML/CSS/JS"],
    tags: ["React.js", "Tailwind CSS", "HTML/CSS/JS", "Productivity"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/task-management-hero.jpg",
    images: [
      "/images/projects/task-board.jpg",
      "/images/projects/task-modal.jpg",
      "/images/projects/task-progress.jpg",
    ],
    features: [
      "Kanban-style task board interface",
      "Drag-and-drop task management",
      "Real-time collaboration features",
      "Progress tracking and analytics",
      "Team assignment and notifications",
      "Task filtering and search",
      "Responsive design for all devices",
      "Firebase real-time database integration",
    ],
    challenges: [
      "Implementing smooth drag-and-drop functionality",
      "Managing real-time data synchronization",
      "Creating intuitive user interfaces for task management",
    ],
    year: "2024",
  },
  {
    id: "rsa-web-app",
    slug: "rsa-web-app",
    title: "RSA Web App",
    description:
      "A web-based tool to encrypt and decrypt messages using RSA algorithm. Features key generation, dark mode, and an easy-to-use UI.",
    longDescription:
      "A comprehensive web application implementing RSA encryption and decryption algorithms. Built with Flask backend and modern frontend technologies, featuring secure key generation, dark mode interface, and user-friendly encryption tools. Serves as both an educational resource and practical cryptography utility for secure communication.",
    tech: ["Flask", "HTML/CSS/JS"],
    tags: ["Flask", "HTML/CSS/JS", "Cryptography"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/rsa-hero.jpg",
    images: [
      "/images/projects/rsa-encryption.jpg",
      "/images/projects/rsa-keygen.jpg",
      "/images/projects/rsa-darkmode.jpg",
    ],
    features: [
      "RSA key generation (multiple bit sizes)",
      "Text encryption and decryption",
      "Dark/light mode toggle",
      "Auto copy-paste functionality",
      "Key export and import",
      "Educational mode with explanations",
      "Responsive web design",
      "Secure key management",
    ],
    challenges: [
      "Implementing RSA algorithm efficiently",
      "Creating user-friendly cryptographic interfaces",
      "Ensuring secure key handling and storage",
    ],
    year: "2024",
  },
  {
    id: "portfolio-template",
    slug: "portfolio-template",
    title: "Portfolio Template",
    description:
      "A minimal, responsive portfolio starter built using HTML, CSS, and JS. Designed to be clean, customizable, and developer-friendly.",
    longDescription:
      "A clean, minimal portfolio template built with vanilla HTML, CSS, and JavaScript. Designed to be easily customizable and developer-friendly, featuring responsive design, smooth animations, and modern layout patterns. Perfect for developers looking for a lightweight, fast-loading portfolio solution without framework dependencies.",
    tech: ["HTML/CSS/JS", "Next.js"],
    tags: ["HTML/CSS/JS", "Next.js", "Template"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/portfolio-template-hero.jpg",
    images: [
      "/images/projects/portfolio-hero.jpg",
      "/images/projects/portfolio-projects.jpg",
      "/images/projects/portfolio-contact.jpg",
    ],
    features: [
      "Clean, minimal design aesthetic",
      "Fully responsive layout",
      "Smooth scroll animations",
      "Project showcase grid",
      "Contact form integration",
      "SEO-friendly structure",
      "Fast loading performance",
      "Easy customization options",
    ],
    challenges: [
      "Creating a versatile template for different use cases",
      "Implementing smooth animations without frameworks",
      "Ensuring cross-browser compatibility",
    ],
    year: "2023",
  },
  {
    id: "weather-application",
    slug: "weather-application",
    title: "Weather Application",
    description: "A live weather forecasting app with real-time API integration, geolocation, and interactive visuals.",
    longDescription:
      "A comprehensive weather application built with vanilla JavaScript featuring real-time API integration, geolocation services, and interactive weather visualizations. Provides accurate forecasts, location-based weather detection, and intuitive user interface for planning and daily weather monitoring.",
    tech: ["HTML/CSS/JS", "React.js"],
    tags: ["HTML/CSS/JS", "React.js", "API Integration"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/weather-hero.jpg",
    images: [
      "/images/projects/weather-forecast.jpg",
      "/images/projects/weather-search.jpg",
      "/images/projects/weather-map.jpg",
    ],
    features: [
      "Real-time weather data and forecasts",
      "Location-based weather detection",
      "Interactive weather maps",
      "7-day forecast with hourly details",
      "Weather search by city",
      "Responsive design for all devices",
      "Weather icons and animations",
      "API integration with weather services",
    ],
    challenges: [
      "Handling API rate limits and error states",
      "Implementing accurate geolocation features",
      "Creating intuitive weather data visualization",
    ],
    year: "2023",
  },
  {
    id: "secure-notepad-app",
    slug: "secure-notepad-app",
    title: "Secure Notepad App",
    description:
      "A secure note-taking app where content is encrypted using a custom algorithm. User must enter a key to decrypt previous sessions.",
    longDescription:
      "A secure note-taking application built with Flask that encrypts user content using custom encryption algorithms. Features session-based encryption, secure key management, and user-friendly interface for creating and accessing encrypted notes. Designed to provide privacy and security for sensitive information storage.",
    tech: ["Flask", "HTML/CSS/JS"],
    tags: ["Flask", "HTML/CSS/JS", "Security"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/secure-notepad-hero.jpg",
    images: [
      "/images/projects/notepad-encryption.jpg",
      "/images/projects/notepad-decrypt.jpg",
      "/images/projects/notepad-dashboard.jpg",
    ],
    features: [
      "Custom encryption algorithm implementation",
      "Session-based note encryption",
      "Secure key management system",
      "User-friendly note editor",
      "Decryption key verification",
      "Responsive web interface",
      "Data privacy and security focus",
      "Simple dashboard for note management",
    ],
    challenges: [
      "Implementing secure encryption algorithms",
      "Managing encryption keys safely",
      "Creating intuitive security-focused user experience",
    ],
    year: "2024",
  },
  {
    id: "simple-youtube-clone",
    slug: "simple-youtube-clone",
    title: "Simple YouTube Clone",
    description:
      "A clean YouTube-inspired frontend using basic HTML, CSS, and JavaScript. Built to practice layout structure and responsive UI elements.",
    longDescription:
      "A YouTube-inspired frontend application built with vanilla HTML, CSS, and JavaScript to practice modern layout structures and responsive design patterns. Features video card grids, navigation components, search functionality, and player interfaces that mimic popular video platforms while focusing on clean code and responsive design principles.",
    tech: ["HTML/CSS/JS"],
    tags: ["HTML/CSS/JS", "Frontend"],
    category: "learning",
    type: "personal",
    status: "Completed",
    image: "/images/projects/youtube-clone-hero.jpg",
    images: [
      "/images/projects/youtube-grid.jpg",
      "/images/projects/youtube-sidebar.jpg",
      "/images/projects/youtube-player.jpg",
    ],
    features: [
      "Video card grid layout",
      "Responsive sidebar navigation",
      "Search functionality interface",
      "Video player mockup design",
      "Mobile-responsive design",
      "Clean, modern UI components",
      "CSS Grid and Flexbox layouts",
      "Interactive hover effects",
    ],
    challenges: [
      "Replicating complex YouTube layout structures",
      "Implementing responsive design without frameworks",
      "Creating smooth user interactions with vanilla JavaScript",
    ],
    year: "2023",
  },
]

export const techFilters = [
  "All",
  "Next.js",
  "React.js",
  "WordPress",
  "Shopify",
  "Firebase",
  "Drupal",
  "Flask",
  "HTML/CSS/JS",
  "Tailwind CSS",
  "Node.js",
  "Bootstrap",
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug)
}

export function getProjectsByTech(tech: string): Project[] {
  if (tech === "All") return projects
  return projects.filter((project) => project.tech.includes(tech) || project.tags.includes(tech))
}

export function getClientProjects(): Project[] {
  return projects.filter((project) => project.type === "client")
}

export function getLearningProjects(): Project[] {
  return projects.filter((project) => project.type === "personal")
}
