export interface Project {
  id: string
  title: string
  description: string
  longDescription: string
  tech: string[]
  tags: string[]
  category: "web-development" | "learning"
  type: "client" | "personal"
  status: "Live" | "Completed" | "In Development"
  url?: string
  github?: string
  image: string
  images?: string[]
  features: string[]
  challenges?: string[]
  year: string
  client?: string
  slug: string
}

export const projects: Project[] = [
  {
    id: "saaranj",
    slug: "saaranj",
    title: "Saaranj",
    description: "Professional business website and digital presence.",
    longDescription: "A comprehensive digital platform for Saaranj, showcasing their services and portfolio. Built with modern web technologies to ensure optimal performance, SEO visibility, and user engagement.",
    tech: ["Next.js", "React", "Tailwind CSS"],
    tags: ["Business Website", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.saaranj.com/",
    image: "/images/projects/saaranj-hero.jpg",
    images: ["/images/projects/saaranj-hero.jpg"],
    features: ["Responsive design", "SEO optimization", "Fast loading times", "Custom UI components"],
    year: "2024",
    client: "Saaranj"
  },
  {
    id: "neo-heights",
    slug: "neo-heights",
    title: "Neo Heights",
    description: "Industrial construction and infrastructure corporate website.",
    longDescription: "A modern corporate website for Neo Heights, highlighting their industrial construction projects, infrastructure capabilities, and structural engineering services. Designed to build trust with large-scale clients.",
    tech: ["Next.js", "React"],
    tags: ["Construction", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.neoheights.com/",
    image: "/images/projects/neo-heights-hero.jpg",
    images: ["/images/projects/neo-heights-hero.jpg"],
    features: ["Project portfolio showcase", "Service details", "Contact forms", "Mobile responsive"],
    year: "2024",
    client: "Neo Heights"
  },
  {
    id: "charge-infra",
    slug: "charge-infra",
    title: "Charge Infra",
    description: "Electric vehicle charging infrastructure solutions.",
    longDescription: "A modern platform for Charge Infra, showcasing their EV charging infrastructure solutions. The site features interactive elements, service information, and a professional design reflecting sustainable transportation.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Infrastructure", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.chargeinfra.com/",
    image: "/images/projects/charge-hero.jpg",
    images: ["/images/projects/charge-hero.jpg"],
    features: ["Service highlights", "Location mapping", "Contact integration", "Performance optimized"],
    year: "2024",
    client: "Charge Infra"
  },
  {
    id: "neo-leather",
    slug: "neo-leather",
    title: "Neo Leather",
    description: "Premium leather furniture brand showcase.",
    longDescription: "A high-performance static website for Neo Leather, a premium furniture brand. Features an elegant product showcase with blazing fast load times and optimized imagery to highlight product quality.",
    tech: ["Next.js", "React", "CSS"],
    tags: ["Furniture", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "http://neoleather.in/",
    image: "/images/projects/neoleather-hero.jpg",
    images: ["/images/projects/neoleather-hero.jpg"],
    features: ["Product catalog", "High-quality image galleries", "Brand storytelling", "Fast performance"],
    year: "2024",
    client: "Neo Leather"
  },
  {
    id: "snip-dark",
    slug: "snip-dark",
    title: "Snip Dark Salon Spa",
    description: "Premium salon and spa digital experience.",
    longDescription: "An elegant website for Snip Dark Salon Spa, featuring service menus, ambiance showcases, and appointment booking information with a luxurious dark aesthetic.",
    tech: ["WordPress"],
    tags: ["Beauty & Wellness", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://snipdark.com/",
    image: "/images/projects/snipdark-hero.jpg",
    images: ["/images/projects/snipdark-hero.jpg"],
    features: ["Service menus", "Visual galleries", "Appointment booking", "Mobile responsive"],
    year: "2024",
    client: "Snip Dark Salon Spa"
  },
  {
    id: "harvis-infra",
    slug: "harvis-infra",
    title: "Harvis Infra",
    description: "Road construction materials and infrastructure solutions.",
    longDescription: "A dynamic web platform for Harvis Infra, showcasing bitumen, steel, cement, and other road construction materials with technical specifications and product details.",
    tech: ["Next.js", "React"],
    tags: ["Construction", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.harvisinfra.com/",
    image: "/images/projects/harvis-hero.jpg",
    images: ["/images/projects/harvis-hero.jpg"],
    features: ["Product specifications", "Industry solutions", "Contact integration", "SEO optimized"],
    year: "2024",
    client: "Harvis Infra"
  },
  {
    id: "samagra-interiors",
    slug: "samagra-interiors",
    title: "Samagra Interiors",
    description: "Premium interior design firm portfolio.",
    longDescription: "A sophisticated web platform for Samagra Interiors, specializing in residential and commercial spaces. Features extensive project galleries and design inspiration.",
    tech: ["Next.js", "React", "Tailwind CSS"],
    tags: ["Interior Design", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.samagrainteriors.com/",
    image: "/images/projects/samagra-hero.jpg",
    images: ["/images/projects/samagra-hero.jpg"],
    features: ["Project galleries", "Service descriptions", "Contact forms", "Responsive layout"],
    year: "2024",
    client: "Samagra Interiors"
  },
  {
    id: "tuff-ppf",
    slug: "tuff-ppf",
    title: "Tuff PPF",
    description: "Paint protection film and automotive care services.",
    longDescription: "A specialized website for Tuff PPF, highlighting their automotive paint protection films, installation services, and vehicle care solutions.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Automotive", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://tuffppf.com/",
    image: "/images/projects/tuffppf-hero.jpg",
    images: ["/images/projects/tuffppf-hero.jpg"],
    features: ["Service details", "Visual showcases", "Booking integration", "Mobile optimized"],
    year: "2024",
    client: "Tuff PPF"
  },
  {
    id: "yuvi-builders",
    slug: "yuvi-builders",
    title: "Yuvi Builders",
    description: "Advanced real estate and property development platform.",
    longDescription: "A comprehensive real estate platform for Yuvi Builders, featuring dynamic property listings, project updates, and filtering systems for prospective buyers.",
    tech: ["Next.js", "React", "Drupal"],
    tags: ["Real Estate", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.yuvibuilders.com/",
    image: "/images/projects/yuvi-hero.jpg",
    images: ["/images/projects/yuvi-hero.jpg"],
    features: ["Property listings", "Advanced filtering", "CMS integration", "SEO optimized"],
    year: "2024",
    client: "Yuvi Builders"
  },
  {
    id: "bangalore-gastro",
    slug: "bangalore-gastro",
    title: "Bangalore Gastro Centre",
    description: "Digital platform for a NABH-accredited hospital.",
    longDescription: "A comprehensive digital platform for Bangalore Gastro Centre featuring doctor listings, appointment booking, health blogs, and robust content management.",
    tech: ["Next.js", "React", "Drupal"],
    tags: ["Healthcare", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.bangaloregastrocentre.com/",
    image: "/images/projects/bgc-hero.jpg",
    images: ["/images/projects/bgc-hero.jpg"],
    features: ["Doctor directories", "Appointment booking", "Health resources", "CMS integration"],
    year: "2024",
    client: "Bangalore Gastro Centre"
  },
  {
    id: "antara-studios",
    slug: "antara-studios",
    title: "Antara Studios",
    description: "Creative agency and digital studio portfolio.",
    longDescription: "A visually striking portfolio for Antara Studios, showcasing their creative campaigns, digital design work, and brand strategy services.",
    tech: ["Next.js", "Framer Motion"],
    tags: ["Business Website", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://antarastudios.com/",
    image: "/images/projects/antara-hero.jpg",
    images: ["/images/projects/antara-hero.jpg"],
    features: ["Dynamic animations", "Portfolio galleries", "Service details", "Responsive design"],
    year: "2024",
    client: "Antara Studios"
  }
  ,
  {
    id: "prasiddhi",
    slug: "prasiddhi",
    title: "Prasiddhi Cloud 9",
    description: "Real estate landing page for lead generation.",
    longDescription: "A high-converting landing page for Prasiddhi Cloud 9, designed to capture leads for their premium real estate project.",
    tech: ["Next.js", "React"],
    tags: ["Real Estate", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://campaign.prasiddhigroup.com/",
    image: "/images/projects/prasiddhi-hero.jpg",
    features: ["Lead generation forms", "Project highlights", "Mobile optimized"],
    year: "2023",
    client: "Prasiddhi Group"
  },
  {
    id: "iconhomz",
    slug: "iconhomz",
    title: "Iconhomz",
    description: "Residential construction and real estate platform.",
    longDescription: "A comprehensive platform for Iconhomz, showcasing their residential projects and apartment complexes.",
    tech: ["WordPress"],
    tags: ["Real Estate", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.iconhomz.com/",
    image: "/images/projects/iconhomz-hero.jpg",
    features: ["Property search", "Project galleries", "Brochure downloads"],
    year: "2023",
    client: "Iconhomz"
  },
  {
    id: "tassels",
    slug: "tassels",
    title: "Tassels",
    description: "Interior design and decor portfolio.",
    longDescription: "A visually rich website for Tassels Interior, showcasing their luxury home decor and interior design services.",
    tech: ["Next.js", "Tailwind CSS"],
    tags: ["Interior Design", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.tasselsinterior.com/",
    image: "/images/projects/tassels-hero.jpg",
    features: ["Visual galleries", "Service breakdown", "Contact forms"],
    year: "2023",
    client: "Tassels"
  },
  {
    id: "look-and-live",
    slug: "look-and-live",
    title: "Look and Live",
    description: "Modern interior design portfolio.",
    longDescription: "A sleek, modern portfolio for Look and Live Interiors, focusing on minimalist design and space planning.",
    tech: ["React.js"],
    tags: ["Interior Design", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.lookandlive.in/",
    image: "/images/projects/lookandlive-hero.jpg",
    features: ["Portfolio showcase", "Testimonials", "Responsive design"],
    year: "2023",
    client: "Look and Live"
  },
  {
    id: "dr-yasaswis",
    slug: "dr-yasaswis",
    title: "Dr. Yasaswi's",
    description: "Specialized healthcare clinic website.",
    longDescription: "A patient-focused website for Dr. Yasaswi's clinic, featuring service information and appointment scheduling.",
    tech: ["Next.js", "Drupal"],
    tags: ["Healthcare", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://dryasaswis.com/",
    image: "/images/projects/yasaswis-hero.jpg",
    features: ["Patient resources", "Service details", "Online booking"],
    year: "2023",
    client: "Dr. Yasaswis"
  },
  {
    id: "shreya-hearings",
    slug: "shreya-hearings",
    title: "Shreya Hearings",
    description: "Hearing care clinic digital presence.",
    longDescription: "A specialized healthcare platform for Shreya Hearings, providing information on hearing loss and available treatments.",
    tech: ["Next.js"],
    tags: ["Healthcare", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://shreya-hearings.vercel.app/",
    image: "/images/projects/shreya-hero.jpg",
    features: ["Service list", "Location finder", "Accessibility focused"],
    year: "2023",
    client: "Shreya Hearings"
  },
  {
    id: "vedaearth",
    slug: "vedaearth",
    title: "Vedaearth Lounge",
    description: "Wellness and spa booking platform.",
    longDescription: "A serene website for Vedaearth Lounge spa, featuring their holistic wellness services and booking system.",
    tech: ["WordPress", "WooCommerce"],
    tags: ["Wellness", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://vedaearthloungespa.com/",
    image: "/images/projects/vedaearth-hero.jpg",
    features: ["Service menu", "Online booking", "E-commerce for products"],
    year: "2023",
    client: "Vedaearth Lounge"
  },
  {
    id: "sangeetha",
    slug: "sangeetha",
    title: "Sangeetha Tyres",
    description: "Automotive services and retail platform.",
    longDescription: "A robust digital storefront for Sangeetha Tyres, showcasing their inventory of tires and automotive services.",
    tech: ["React.js", "Node.js"],
    tags: ["Automotive", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.sangeethatyres.in/",
    image: "/images/projects/sangeetha-hero.jpg",
    features: ["Product catalog", "Service booking", "Location details"],
    year: "2023",
    client: "Sangeetha Tyres"
  },
  {
    id: "turbo-car",
    slug: "turbo-car",
    title: "Turbo Car Care",
    description: "Premium car detailing and care services.",
    longDescription: "A high-octane website for Turbo Car Care, highlighting their detailing, ceramic coating, and modification services.",
    tech: ["WordPress"],
    tags: ["Automotive", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.turbocarcare.in/",
    image: "/images/projects/turbo-hero.jpg",
    features: ["Service packages", "Before/After gallery", "Booking system"],
    year: "2023",
    client: "Turbo Car Care"
  },
  {
    id: "miracle-stonex",
    slug: "miracle-stonex",
    title: "Miracle Stonex",
    description: "Premium granite and stone manufacturer.",
    longDescription: "An elegant showcase for Miracle Stonex, featuring high-resolution galleries of their premium stone products.",
    tech: ["React.js"],
    tags: ["Construction", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://www.miraclestonex.com/",
    image: "/images/projects/miracle-hero.jpg",
    features: ["Product catalog", "Material specs", "B2B inquiry forms"],
    year: "2023",
    client: "Miracle Stonex"
  },
  {
    id: "teachers-by-choice",
    slug: "teachers-by-choice",
    title: "Teachers By Choice",
    description: "Educational platform for private educators.",
    longDescription: "A dynamic web app matching students with qualified private educators and tutors.",
    tech: ["Next.js", "Node.js", "MongoDB"],
    tags: ["Web App", "Client Project"],
    category: "web-development",
    type: "client",
    status: "Live",
    url: "https://teachersbychoice.vercel.app/",
    image: "/images/projects/teachers-hero.jpg",
    features: ["Tutor search", "User profiles", "Messaging system"],
    year: "2023",
    client: "Teachers By Choice"
  }

]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug)
}

export function getAllTags(): string[] {
  const tags = new Set<string>()
  projects.forEach((project) => {
    project.tags.forEach((tag) => tags.add(tag))
  })
  return Array.from(tags)
}
